# Generated by Django 2.1.11 on 2020-01-26 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191227_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
