# Generated by Django 2.1.11 on 2020-01-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_premium_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_link_1',
            field=models.URLField(blank=True, verbose_name='Personal Website Link 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_link_2',
            field=models.URLField(blank=True, verbose_name='Personal Website Link 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_link_3',
            field=models.URLField(blank=True, verbose_name='Personal Website Link 3'),
        ),
    ]
