# Generated by Django 2.1.11 on 2020-01-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_specialism'),
        ('users', '0004_auto_20200128_2151'),
    ]

    operations = [
    ]
