# Generated by Django 2.1.11 on 2020-04-08 11:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('browser_family', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=10)),
                ('os_family', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=10)),
                ('device_family', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=models.SET('Anonymous'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=20)),
                ('seen', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='charity_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedbacker_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='most_common_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=30),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='most_common_words_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=30),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='new_feedbackee_message',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='new_feedbacker_message',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='feedback_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeedbackRequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='other_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_trigger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeedbackRequest'),
        ),
    ]
