# Generated by Django 2.1.11 on 2020-01-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedbackrequest_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Area'),
        ),
    ]
