# Generated by Django 2.2.4 on 2019-10-14 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_feedbackrequest_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='feedbackrequest',
            old_name='date',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='date_completed',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedbacker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='request_feedbacker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='time_limit',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedbackee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_feedbackee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeedbackRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeedbackRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('feedbackee', models.ForeignKey(on_delete=models.SET('Anonymous'), related_name='rating_feedbackee', to=settings.AUTH_USER_MODEL)),
                ('feedbacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_feedbacker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackerCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FeedbackRequest')),
                ('feedbacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
