# Generated by Django 2.1.11 on 2020-06-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200408_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackercandidate',
            name='proposed_reward',
            field=models.IntegerField(default=0),
        ),
    ]
