# Generated by Django 2.2.4 on 2019-10-17 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191014_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedbacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_feedbacker', to=settings.AUTH_USER_MODEL),
        ),
    ]
