# Generated by Django 2.2.4 on 2019-11-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedbacker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackerComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacker_comments', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedbacker_comments',
            field=models.TextField(default=''),
        ),
    ]
