# Generated by Django 2.1.11 on 2020-01-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200129_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackercandidate',
            name='application',
            field=models.CharField(default='', max_length=300),
        ),
    ]
