# Generated by Django 2.1.11 on 2019-12-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191110_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedbackee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_feedbackee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedbacker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='request_feedbacker', to=settings.AUTH_USER_MODEL),
        ),
    ]
