# Generated by Django 2.1.11 on 2019-12-24 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191224_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedbacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_feedbacker', to=settings.AUTH_USER_MODEL),
        ),
    ]
