# Generated by Django 2.1.11 on 2019-12-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191110_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbacker',
        ),
    ]
