# Generated by Django 2.1.11 on 2020-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191227_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='comment',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
