# Generated by Django 2.1.11 on 2020-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200115_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedbacker_rated',
            field=models.IntegerField(default=0),
        ),
    ]
